#!/usr/bin/env bash

echo "Running pre-commit hook..."

# Check if mvn command exists
if ! command -v mvn > /dev/null 2>&1; then
  echo "mvn command not found. Please install Maven and ensure it is in your PATH."
  exit 1
fi

echo "Maven command found."

# Run Format check
mvn spotless:check

# Check the result of the Format check
if [ $? -ne 0 ]; then
  echo "Formatting check failed, applying formatter..."
  mvn spotless:apply
  echo "Code formatting check failed, so formatter has been run."
  echo "Please check and commit any newly formatted files, then commit again!"
  exit 1
fi

echo "Formatting check passed."

# If check passes, allow the commit
exit 0